apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: pv-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mgabs"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "mgabs"
            - name: MONGO_DB_NAME
              value: "proyectoV"